apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-application
  namespace: argocd
  labels:
    environment: dev
spec:
  project: default
  
  source:
    repoURL: https://github.com/Ice-Bear-Institute/terraform-golden-repo
    targetRevision: HEAD
    path: helm/charts/app-chart
    helm:
      valueFiles:
      - values.yaml
      values: |
        environment: dev
        replicaCount: 1
        
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    
  revisionHistoryLimit: 3